version: '3'

services:
  registry:
    image: docker.io/registry
    environment: 
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
      - REGISTRY_AUTH=token
      - REGISTRY_AUTH_TOKEN_REALM=https://localhost:8443/docker-token-auth/
      - REGISTRY_AUTH_TOKEN_SERVICE="127.0.0.1:5000"
      - REGISTRY_AUTH_TOKEN_ISSUER='127.0.0.1'
      - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/pki/ca_bundle.crt
    volumes:
      - ./pki/ca_bundle.crt:/pki/ca_bundle.crt
    ports:
      - "5000:5000"
  db:
    image: docker.io/postgres
  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=settings_prd
    command: |
      gunicorn --bind 0.0.0.0:8443
      --certfile=/app/pki/issued/django.crt 
      --keyfile=/app/pki/private/django.key wsgi
      --access-logfile -
    volumes:
      - ./pki/private/django.key:/app/pki/private/django.key:ro
      - ./pki/issued/django.crt:/app/pki/issued/django.crt:ro
      - ./pki/private/token.key:/app/pki/private/token.key:ro
      - ./pki/issued/token.crt:/app/pki/issued/token.crt:ro
      - ./settings_prd.py:/app/settings_prd.py:ro
    ports:
      - "8443:8443"
    depends_on:
      - db
      - registry
